// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // For Prisma CLI (db push/migrate): use the Supavisor Session Pooler (port 5432, no pgbouncer param)
    // Session Pooler preserves connection state and supports DDL, unlike Transaction Pooler (port 6543)
    // The app runtime (PrismaClient) uses DATABASE_URL (Transaction Pooler) via src/lib/db.ts
    url: process.env["DIRECT_URL"],
  },
});
